version: '3.8'

services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=autonomous_code_improver
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - autonomous-code-improver-network

volumes:
  postgres_data:

networks:
  autonomous-code-improver-network:
    driver: bridge
