version: '3.8'

services:
  nats:
    image: nats:2.10-alpine
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_data:/data
    command: |
      -js
      -sd /data
      -m 8222
    networks:
      - autonomous-code-improver-network

volumes:
  nats_data:

networks:
  autonomous-code-improver-network:
    driver: bridge

