version: '3.8'

services:
  neo4j:
    image: neo4j:5.10-community
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./init.cypher:/init.cypher
    networks:
      - autonomous-code-improver-network

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  autonomous-code-improver-network:
    driver: bridge
