name: Security

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Mondays

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install safety bandit trivy
    
    - name: Run safety check
      run: |
        safety check --json --output safety-report.json || true
    
    - name: Run bandit security scan
      run: |
        bandit -r agent/ -f json -o bandit-report.json || true
    
    - name: Run Trivy vulnerability scanner
      run: |
        trivy fs --format json --output trivy-report.json . || true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: security-reports
        path: |
          safety-report.json
          bandit-report.json
          trivy-report.json
    
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      with:
        config-path: .gitleaks.toml
        report-path: gitleaks-report.json
      if: always()
    
    - name: Upload Gitleaks report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: gitleaks-report
        path: gitleaks-report.json

  container-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t autonomous-code-improver:latest .
    
    - name: Run Trivy on container
      run: |
        trivy image --format json --output container-trivy-report.json autonomous-code-improver:latest || true
    
    - name: Upload container scan report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: container-trivy-report
        path: container-trivy-report.json
